imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    csrf_protection: false
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false
