security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: md5
            iterations: 0
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        simple_form:
            id: acme.simple_form_authenticator
        simple_apikey:
            id: acme.simple_apikey_authenticator

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/demo/secured/
#            simple_http:
#                provider: simple_apikey
#                authenticator: acme.simple_apikey_authenticator
            simple_form:
                provider: simple_form
                authenticator: acme.simple_form_authenticator
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            anonymous: ~

    access_control:
        - { path: ^/demo/secured/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/demo/secured, roles: ROLE_USER }
